import os
import numpy as np

# core framework
DEBUG = False
SHOW_PLOT = False
RESULTS_FOLDER = os.sep + "results" + os.sep
WRITE_ALL_INDIVIDUALS = True
LOG_FILE = "." + os.sep + "log.txt"
BACKUP_FOLDER = "backup"
EXPERIMENTAL_MODE = False

# backup options
BACKUP_ITERATIONS = True
BACKUP_PROBLEM = True
BACKUP_RESULT = False

# analysis module
N_CELLS = 10
CONSIDER_HIGH_VAL_OS_PLOT = True
PENALTY_MAX = 1000
PENALTY_MIN = -1000 
WRITE_ALL_INDIVIDUALS = True
LAST_ITERATION_ONLY_DEFAULT = True
LAST_ITERATION_ONLY = True
METRIC_PLOTS_FOLDER = "metrics" + os.sep
COVERAGE_METRIC_NAME = "CID"
LOAD_FROM_GENERATIONS = True

METRIC_CONFIG = {}
METRIC_CONFIG["DUMMY"] = dict(
    ref_point_hv = np.asarray([20,0]),
    ideal = np.asarray([0,-20])
)

# output
MODE_WRITE_SIMOUT = "all"
MODE_WRITE_GIF = "opt"
MODE_PLOT_TIME_TRACES = "opt"

NUM_SIMOUT_MAX = 10000
NUM_GIF_MAX = 7
NUM_PLOT_TIME_TRACES = 10

DEFAULT_CAR_LENGTH = 4.89
DEFAULT_CAR_WIDTH = 1.9
DEFAULT_PEDESTRIAN_SIZE = 0.4

DEFAULT_TRACE_INTERVAL = 0.05 # in seconds

DUPLICATE_COMP_PRECISION = 8
OUTPUT_PRECISION = 8